name: Scrape latest data

on:
  workflow_dispatch:
  schedule:
    # run it twice per day just to combat flakiness
    - cron: '38 8,17 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.6.16"
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Fetch latest data
      env:
        LLM_GEMINI_KEY: ${{ secrets.LLM_GEMINI_KEY }}
      run: LLM_GEMINI_KEY=$LLM_GEMINI_KEY ./scrape.sh
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(TZ=America/Anchorage date)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push